/** @type {import('tailwindcss').Config} */
export default {
    darkMode: "class",
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                "primary-fixed-dim": "#454747",
                "on-surface": "#e2e2e2",
                "error-container": "#93000a",
                "on-secondary-fixed-variant": "#3a3c3c",
                "secondary-fixed": "#c6c6c7",
                "primary-container": "#d4d4d4",
                "on-primary": "#1a1c1c",
                "inverse-on-surface": "#303030",
                "outline": "#919191",
                "tertiary-fixed": "#5d5f5f",
                "primary-fixed": "#5d5f5f",
                "on-primary-container": "#000000",
                "surface-container-highest": "#353535",
                "inverse-primary": "#5d5f5f",
                "tertiary-container": "#909191",
                "surface-bright": "#393939",
                "inverse-surface": "#e2e2e2",
                "on-tertiary-fixed": "#ffffff",
                "on-background": "#e2e2e2",
                "secondary-container": "#454747",
                "tertiary-fixed-dim": "#454747",
                "secondary": "#c6c6c7",
                "primary": "#ffffff",
                "on-tertiary": "#1a1c1c",
                "tertiary": "#e2e2e2",
                "on-error": "#690005",
                "on-secondary": "#1a1c1c",
                "on-secondary-container": "#e2e2e2",
                "on-tertiary-fixed-variant": "#e2e2e2",
                "on-primary-fixed": "#ffffff",
                "surface-container-high": "#2a2a2a",
                "surface-container": "#1f1f1f",
                "on-surface-variant": "#c6c6c6",
                "surface-tint": "#c6c6c7",
                "error": "#ffb4ab",
                "on-secondary-fixed": "#1a1c1c",
                "outline-variant": "#474747",
                "secondary-fixed-dim": "#aaabab",
                "surface-variant": "#353535",
                "on-tertiary-container": "#000000",
                "surface-dim": "#131313",
                "surface-container-low": "#1b1b1b",
                "surface-container-lowest": "#0e0e0e",
                "on-error-container": "#ffdad6",
                "on-primary-fixed-variant": "#e2e2e2",
                "background": "#131313",
                "surface": "#131313"
            },
            fontFamily: {
                "headline": ["Inter"],
                "body": ["Inter"],
                "label": ["Space Grotesk"],
                "mono": ["JetBrains Mono"]
            },
            borderRadius: {
                "DEFAULT": "0px",
                "lg": "0px",
                "xl": "0px",
                "full": "0px"
            },
        },
    },
    plugins: [],
}
